// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "notifydialog.h"
#include <config.h>
#include "notify.h"

Fl_Group *grpNotifyEvent=(Fl_Group *)0;

Fl_Choice *mnuNotifyEvent=(Fl_Choice *)0;

Fl_Light_Button *btnNotifyEnabled=(Fl_Light_Button *)0;

Fl_Input2 *inpNotifyRE=(Fl_Input2 *)0;

Fl_Group *grpNotifyFilter=(Fl_Group *)0;

Fl_Round_Button *chkNotifyFilterCall=(Fl_Round_Button *)0;

static void cb_chkNotifyFilterCall(Fl_Round_Button* o, void*) {
  if (!o->value()) {
    o->value(1);
    return;
}
inpNotifyFilterCall->show();
btnNotifyFilterDXCC->hide();
chkNotifyFilterDXCC->value(0);
}

Fl_Input2 *inpNotifyFilterCall=(Fl_Input2 *)0;

Fl_Round_Button *chkNotifyFilterDXCC=(Fl_Round_Button *)0;

static void cb_chkNotifyFilterDXCC(Fl_Round_Button* o, void*) {
  if (!o->value()) {
    o->value(1);
    return;
}
inpNotifyFilterCall->hide();
btnNotifyFilterDXCC->show();
chkNotifyFilterCall->value(0);
}

Fl_Button *btnNotifyFilterDXCC=(Fl_Button *)0;

Fl_Check_Button *chkNotifyFilterNWB=(Fl_Check_Button *)0;

Fl_Check_Button *chkNotifyFilterLOTW=(Fl_Check_Button *)0;

Fl_Check_Button *chkNotifyFilterEQSL=(Fl_Check_Button *)0;

Fl_Group *grpNotifyAction=(Fl_Group *)0;

Fl_Input2 *inpNotifyActionDialog=(Fl_Input2 *)0;

Fl_Input2 *inpNotifyActionProgram=(Fl_Input2 *)0;

Fl_Button *btnNotifyActionProgram=(Fl_Button *)0;

Fl_Spinner *cntNotifyActionLimit=(Fl_Spinner *)0;

Fl_Input2 *inpNotifyActionMacro=(Fl_Input2 *)0;

Fl_Button *btnNotifyActionMacro=(Fl_Button *)0;

Fl_Button *btnNotifyActionDialogDefault=(Fl_Button *)0;

Fl_Spinner *cntNotifyActionDialogTimeout=(Fl_Spinner *)0;

Fl_Button *btnNotifyAdd=(Fl_Button *)0;

Fl_Button *btnNotifyRemove=(Fl_Button *)0;

Fl_Button *btnNotifyUpdate=(Fl_Button *)0;

Table *tblNotifyList=(Table *)0;

Fl_Button *btnNotifyTest=(Fl_Button *)0;

Fl_Group *grpNotifyDup=(Fl_Group *)0;

Fl_Check_Button *chkNotifyDupIgnore=(Fl_Check_Button *)0;

Fl_Choice *mnuNotifyDupWhich=(Fl_Choice *)0;

Fl_Spinner *cntNotifyDupTime=(Fl_Spinner *)0;

Fl_Check_Button *chkNotifyDupBand=(Fl_Check_Button *)0;

Fl_Check_Button *chkNotifyDupMode=(Fl_Check_Button *)0;

Fl_Double_Window* make_notify_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(500, 450, "Notifications");
    w = o;
    { grpNotifyEvent = new Fl_Group(2, 2, 219, 126, "Event");
      grpNotifyEvent->box(FL_ENGRAVED_FRAME);
      grpNotifyEvent->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      { mnuNotifyEvent = new Fl_Choice(36, 29, 175, 22);
        mnuNotifyEvent->down_box(FL_BORDER_BOX);
      } // Fl_Choice* mnuNotifyEvent
      { btnNotifyEnabled = new Fl_Light_Button(131, 94, 80, 23, "Enabled");
      } // Fl_Light_Button* btnNotifyEnabled
      { Fl_Input2* o = inpNotifyRE = new Fl_Input2(36, 61, 175, 23, "RE:");
        inpNotifyRE->box(FL_DOWN_BOX);
        inpNotifyRE->color(FL_BACKGROUND2_COLOR);
        inpNotifyRE->selection_color(FL_SELECTION_COLOR);
        inpNotifyRE->labeltype(FL_NORMAL_LABEL);
        inpNotifyRE->labelfont(0);
        inpNotifyRE->labelsize(14);
        inpNotifyRE->labelcolor(FL_FOREGROUND_COLOR);
        inpNotifyRE->align(FL_ALIGN_LEFT);
        inpNotifyRE->when(FL_WHEN_RELEASE);
        o->labelsize(FL_NORMAL_SIZE);
      } // Fl_Input2* inpNotifyRE
      grpNotifyEvent->end();
    } // Fl_Group* grpNotifyEvent
    { grpNotifyFilter = new Fl_Group(2, 130, 219, 176, "Filter");
      grpNotifyFilter->box(FL_ENGRAVED_FRAME);
      grpNotifyFilter->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      { chkNotifyFilterCall = new Fl_Round_Button(12, 157, 80, 20, "Callsign");
        chkNotifyFilterCall->down_box(FL_ROUND_DOWN_BOX);
        chkNotifyFilterCall->callback((Fl_Callback*)cb_chkNotifyFilterCall);
      } // Fl_Round_Button* chkNotifyFilterCall
      { inpNotifyFilterCall = new Fl_Input2(131, 157, 80, 20);
        inpNotifyFilterCall->box(FL_DOWN_BOX);
        inpNotifyFilterCall->color(FL_BACKGROUND2_COLOR);
        inpNotifyFilterCall->selection_color(FL_SELECTION_COLOR);
        inpNotifyFilterCall->labeltype(FL_NORMAL_LABEL);
        inpNotifyFilterCall->labelfont(0);
        inpNotifyFilterCall->labelsize(14);
        inpNotifyFilterCall->labelcolor(FL_FOREGROUND_COLOR);
        inpNotifyFilterCall->align(FL_ALIGN_CENTER);
        inpNotifyFilterCall->when(FL_WHEN_RELEASE);
      } // Fl_Input2* inpNotifyFilterCall
      { chkNotifyFilterDXCC = new Fl_Round_Button(12, 186, 110, 20, "DXCC entity");
        chkNotifyFilterDXCC->down_box(FL_ROUND_DOWN_BOX);
        chkNotifyFilterDXCC->callback((Fl_Callback*)cb_chkNotifyFilterDXCC);
      } // Fl_Round_Button* chkNotifyFilterDXCC
      { btnNotifyFilterDXCC = new Fl_Button(183, 183, 28, 23);
        btnNotifyFilterDXCC->tooltip("Show DXCC entities");
      } // Fl_Button* btnNotifyFilterDXCC
      { chkNotifyFilterNWB = new Fl_Check_Button(12, 216, 155, 20, "Not worked before");
        chkNotifyFilterNWB->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* chkNotifyFilterNWB
      { chkNotifyFilterLOTW = new Fl_Check_Button(12, 246, 100, 20, "LotW user");
        chkNotifyFilterLOTW->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* chkNotifyFilterLOTW
      { chkNotifyFilterEQSL = new Fl_Check_Button(12, 276, 100, 20, "eQSL user");
        chkNotifyFilterEQSL->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* chkNotifyFilterEQSL
      grpNotifyFilter->end();
    } // Fl_Group* grpNotifyFilter
    { grpNotifyAction = new Fl_Group(222, 2, 276, 304, "Action");
      grpNotifyAction->box(FL_ENGRAVED_FRAME);
      grpNotifyAction->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      { Fl_Input2* o = inpNotifyActionDialog = new Fl_Input2(233, 42, 218, 60, "Show alert text:");
        inpNotifyActionDialog->type(4);
        inpNotifyActionDialog->box(FL_DOWN_BOX);
        inpNotifyActionDialog->color(FL_BACKGROUND2_COLOR);
        inpNotifyActionDialog->selection_color(FL_SELECTION_COLOR);
        inpNotifyActionDialog->labeltype(FL_NORMAL_LABEL);
        inpNotifyActionDialog->labelfont(0);
        inpNotifyActionDialog->labelsize(14);
        inpNotifyActionDialog->labelcolor(FL_FOREGROUND_COLOR);
        inpNotifyActionDialog->align(FL_ALIGN_TOP_LEFT);
        inpNotifyActionDialog->when(FL_WHEN_RELEASE);
        o->labelsize(FL_NORMAL_SIZE);
      } // Fl_Input2* inpNotifyActionDialog
      { Fl_Input2* o = inpNotifyActionProgram = new Fl_Input2(234, 243, 218, 23, "Run program:");
        inpNotifyActionProgram->box(FL_DOWN_BOX);
        inpNotifyActionProgram->color(FL_BACKGROUND2_COLOR);
        inpNotifyActionProgram->selection_color(FL_SELECTION_COLOR);
        inpNotifyActionProgram->labeltype(FL_NORMAL_LABEL);
        inpNotifyActionProgram->labelfont(0);
        inpNotifyActionProgram->labelsize(14);
        inpNotifyActionProgram->labelcolor(FL_FOREGROUND_COLOR);
        inpNotifyActionProgram->align(FL_ALIGN_TOP_LEFT);
        inpNotifyActionProgram->when(FL_WHEN_RELEASE);
        o->labelsize(FL_NORMAL_SIZE);
      } // Fl_Input2* inpNotifyActionProgram
      { btnNotifyActionProgram = new Fl_Button(461, 243, 28, 23);
      } // Fl_Button* btnNotifyActionProgram
      { cntNotifyActionLimit = new Fl_Spinner(399, 276, 52, 20, "Trigger limit (s):");
        cntNotifyActionLimit->tooltip("Minimum time between events");
        cntNotifyActionLimit->minimum(0);
        cntNotifyActionLimit->maximum(3600);
        cntNotifyActionLimit->value(1);
      } // Fl_Spinner* cntNotifyActionLimit
      { Fl_Input2* o = inpNotifyActionMacro = new Fl_Input2(234, 159, 218, 60, "Append to TX text:");
        inpNotifyActionMacro->type(4);
        inpNotifyActionMacro->box(FL_DOWN_BOX);
        inpNotifyActionMacro->color(FL_BACKGROUND2_COLOR);
        inpNotifyActionMacro->selection_color(FL_SELECTION_COLOR);
        inpNotifyActionMacro->labeltype(FL_NORMAL_LABEL);
        inpNotifyActionMacro->labelfont(0);
        inpNotifyActionMacro->labelsize(14);
        inpNotifyActionMacro->labelcolor(FL_FOREGROUND_COLOR);
        inpNotifyActionMacro->align(FL_ALIGN_TOP_LEFT);
        inpNotifyActionMacro->when(FL_WHEN_RELEASE);
        o->labelsize(FL_NORMAL_SIZE);
      } // Fl_Input2* inpNotifyActionMacro
      { btnNotifyActionMacro = new Fl_Button(461, 176, 28, 23);
        btnNotifyActionMacro->tooltip("Show macro editor");
      } // Fl_Button* btnNotifyActionMacro
      { btnNotifyActionDialogDefault = new Fl_Button(461, 61, 28, 23);
        btnNotifyActionDialogDefault->tooltip("Insert default text");
      } // Fl_Button* btnNotifyActionDialogDefault
      { cntNotifyActionDialogTimeout = new Fl_Spinner(399, 112, 52, 20, "Hide after (s):");
        cntNotifyActionDialogTimeout->minimum(0);
        cntNotifyActionDialogTimeout->maximum(3600);
        cntNotifyActionDialogTimeout->value(5);
      } // Fl_Spinner* cntNotifyActionDialogTimeout
      grpNotifyAction->end();
    } // Fl_Group* grpNotifyAction
    { btnNotifyAdd = new Fl_Button(5, 313, 80, 23);
    } // Fl_Button* btnNotifyAdd
    { btnNotifyRemove = new Fl_Button(90, 313, 80, 23);
    } // Fl_Button* btnNotifyRemove
    { btnNotifyUpdate = new Fl_Button(5, 342, 80, 23);
    } // Fl_Button* btnNotifyUpdate
    { tblNotifyList = new Table(2, 372, 496, 76);
      tblNotifyList->box(FL_UP_FRAME);
      tblNotifyList->color(FL_BACKGROUND_COLOR);
      tblNotifyList->selection_color(FL_SELECTION_COLOR);
      tblNotifyList->labeltype(FL_NORMAL_LABEL);
      tblNotifyList->labelfont(0);
      tblNotifyList->labelsize(14);
      tblNotifyList->labelcolor(FL_FOREGROUND_COLOR);
      tblNotifyList->align(FL_ALIGN_CENTER);
      tblNotifyList->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(tblNotifyList);
    } // Table* tblNotifyList
    { btnNotifyTest = new Fl_Button(90, 342, 80, 23);
    } // Fl_Button* btnNotifyTest
    { grpNotifyDup = new Fl_Group(173, 308, 325, 60);
      grpNotifyDup->box(FL_ENGRAVED_FRAME);
      { chkNotifyDupIgnore = new Fl_Check_Button(183, 316, 145, 19, "Ignore duplicates");
        chkNotifyDupIgnore->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* chkNotifyDupIgnore
      { mnuNotifyDupWhich = new Fl_Choice(368, 316, 120, 20, "in:");
        mnuNotifyDupWhich->down_box(FL_BORDER_BOX);
      } // Fl_Choice* mnuNotifyDupWhich
      { cntNotifyDupTime = new Fl_Spinner(248, 345, 60, 20, "Time (s):");
        cntNotifyDupTime->minimum(0);
        cntNotifyDupTime->maximum(97200);
        cntNotifyDupTime->value(600);
      } // Fl_Spinner* cntNotifyDupTime
      { chkNotifyDupBand = new Fl_Check_Button(335, 345, 65, 20, "Band");
        chkNotifyDupBand->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* chkNotifyDupBand
      { chkNotifyDupMode = new Fl_Check_Button(428, 345, 60, 20, "Mode");
        chkNotifyDupMode->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* chkNotifyDupMode
      grpNotifyDup->end();
    } // Fl_Group* grpNotifyDup
    o->size_range(500, 450);
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Button *btnNotifyDXCCSelect=(Fl_Button *)0;

Fl_Button *btnNotifyDXCCDeselect=(Fl_Button *)0;

Table *tblNotifyFilterDXCC=(Table *)0;

Fl_Input2 *inpNotifyDXCCSearchCountry=(Fl_Input2 *)0;

Fl_Input2 *inpNotifyDXCCSearchCallsign=(Fl_Input2 *)0;

Fl_Double_Window* make_dxcc_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(400, 450, "DXCC entities");
    w = o;
    { btnNotifyDXCCSelect = new Fl_Button(10, 382, 90, 23, "Select all");
    } // Fl_Button* btnNotifyDXCCSelect
    { btnNotifyDXCCDeselect = new Fl_Button(10, 417, 90, 23, "Deselect all");
    } // Fl_Button* btnNotifyDXCCDeselect
    { tblNotifyFilterDXCC = new Table(2, 2, 396, 370);
      tblNotifyFilterDXCC->box(FL_UP_FRAME);
      tblNotifyFilterDXCC->color(FL_BACKGROUND_COLOR);
      tblNotifyFilterDXCC->selection_color(FL_SELECTION_COLOR);
      tblNotifyFilterDXCC->labeltype(FL_NORMAL_LABEL);
      tblNotifyFilterDXCC->labelfont(0);
      tblNotifyFilterDXCC->labelsize(14);
      tblNotifyFilterDXCC->labelcolor(FL_FOREGROUND_COLOR);
      tblNotifyFilterDXCC->align(FL_ALIGN_CENTER);
      tblNotifyFilterDXCC->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(tblNotifyFilterDXCC);
    } // Table* tblNotifyFilterDXCC
    { Fl_Input2* o = inpNotifyDXCCSearchCountry = new Fl_Input2(270, 382, 120, 23, "Country search:");
      inpNotifyDXCCSearchCountry->tooltip("Press return to continue the search");
      inpNotifyDXCCSearchCountry->box(FL_DOWN_BOX);
      inpNotifyDXCCSearchCountry->color(FL_BACKGROUND2_COLOR);
      inpNotifyDXCCSearchCountry->selection_color(FL_SELECTION_COLOR);
      inpNotifyDXCCSearchCountry->labeltype(FL_NORMAL_LABEL);
      inpNotifyDXCCSearchCountry->labelfont(0);
      inpNotifyDXCCSearchCountry->labelsize(14);
      inpNotifyDXCCSearchCountry->labelcolor(FL_FOREGROUND_COLOR);
      inpNotifyDXCCSearchCountry->align(FL_ALIGN_LEFT);
      inpNotifyDXCCSearchCountry->when(FL_WHEN_RELEASE);
      o->labelsize(FL_NORMAL_SIZE);
    } // Fl_Input2* inpNotifyDXCCSearchCountry
    { Fl_Input2* o = inpNotifyDXCCSearchCallsign = new Fl_Input2(270, 417, 120, 23, "Prefix search:");
      inpNotifyDXCCSearchCallsign->box(FL_DOWN_BOX);
      inpNotifyDXCCSearchCallsign->color(FL_BACKGROUND2_COLOR);
      inpNotifyDXCCSearchCallsign->selection_color(FL_SELECTION_COLOR);
      inpNotifyDXCCSearchCallsign->labeltype(FL_NORMAL_LABEL);
      inpNotifyDXCCSearchCallsign->labelfont(0);
      inpNotifyDXCCSearchCallsign->labelsize(14);
      inpNotifyDXCCSearchCallsign->labelcolor(FL_FOREGROUND_COLOR);
      inpNotifyDXCCSearchCallsign->align(FL_ALIGN_LEFT);
      inpNotifyDXCCSearchCallsign->when(FL_WHEN_RELEASE);
      o->labelsize(FL_NORMAL_SIZE);
    } // Fl_Input2* inpNotifyDXCCSearchCallsign
    o->size_range(300, 400);
    o->end();
  } // Fl_Double_Window* o
  return w;
}
