// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef debug_dialog_h
#define debug_dialog_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include "debug.h"
extern Fl_Choice *mnu_debug_level;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_clear_debug;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *source_code[15];
#include <FL/Fl_Browser.H>
extern Fl_Browser *btext;
Fl_Double_Window* debug_dialog();
#endif
