// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef dx_dialog_h
#define dx_dialog_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include "flinput2.h"
extern Fl_Input2 *inp_dxcc_host_url;
extern Fl_Input2 *inp_dccc_host_port;
extern Fl_Input2 *inp_dccc_login;
#include <FL/Fl_Check_Button.H>
#include "status.h"
extern Fl_Check_Button *btn_dxcc_connect;
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *brws_dx_cluster;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_dxc_cluster_clear;
extern Fl_Browser *brws_tcpip_stream;
extern Fl_Button *btn_dxc_tcpip_clear;
extern Fl_Browser *brws_dxc_wwv;
extern Fl_Button *btn_dxc_wwv_query;
extern Fl_Button *btn_dxc_wwv_clear;
extern Fl_Browser *brws_dxc_help;
extern Fl_Button *btn_dxc_help_query;
extern Fl_Input2 *inp_help_string;
extern Fl_Button *btn_dxc_help_clear;
extern Fl_Input2 *inp_dxcluster_cmd;
extern Fl_Button *btn_cluster_submit;
extern Fl_Button *btn_cluster_spot;
Fl_Double_Window* dxc_window();
#endif
