// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef PskSquelch_h
#define PskSquelch_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *btnSquelchOnOff;
extern Fl_Light_Button *btnAfcOnOff;
#include <FL/Fl_Button.H>
extern Fl_Button *PskDialogDismiss;
#include <FL/Fl_Slider.H>
extern Fl_Slider *sldrSquelch;
#include <FL/Fl_Progress.H>
extern Fl_Progress *prgsSquelch;
Fl_Double_Window* PskSquelch_dialog();
extern void openSquelchDialog();
extern void createSquelchDialog();
#endif
