// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef ScopeDialog_h
#define ScopeDialog_h

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "digiscope.h"
#include <FL/Fl_Button.H>

extern Fl_Button		*btnCloseScope;
extern Fl_Button		*btnDispType;
extern Fl_Double_Window	*ScopeDialog;
extern Digiscope		*digiscope;
extern void	createScopeDialog();
extern void ShowScope();

#endif
